name: Deploy
on:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches: master

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Install Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Install step
              run: 'deno install --allow-scripts=npm:sharp'

            - name: Disable Astro telemetry
              run: 'deno task disable-telemetry'

            - name: Build step
              run: 'deno task build'

            - name: Upload to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: 'deno-astro-template-i1'
                  entrypoint: 'server/entry.mjs'
                  root: 'dist'
